<script setup lang="ts">
import { reactive, ref } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getCurrentRecord, exitVehicle } from '@/api/operator'
import type { ParkingRecord } from '@/types/parking'
import { PAYMENT_STATUS, RECORD_STATUS } from '@/constants/enums'
import { formatDateTime, formatMoney } from '@/utils/format'
import ConfirmButton from '@/components/common/ConfirmButton.vue'
import StatusTag from '@/components/common/StatusTag.vue'

const searching=ref(false);const exiting=ref(false);const record=ref<ParkingRecord>();const formRef=ref<FormInstance>();const query=reactive({plateNumber:'京A12345'});const manual=reactive({visible:false,reason:''});const rules:FormRules={plateNumber:[{required:true,message:'请输入车牌',trigger:'blur'}]}
async function search(){if(!await formRef.value?.validate())return;searching.value=true;try{record.value=await getCurrentRecord(query.plateNumber)}finally{searching.value=false}}
async function normalExit(){if(!record.value||exiting.value)return;exiting.value=true;try{await exitVehicle({parkingRecordId:record.value.id,action:'NORMAL_EXIT'});ElMessage.success('车辆已正常出场，车位已释放');record.value=undefined}finally{exiting.value=false}}
async function manualRelease(){if(!record.value||!manual.reason.trim()){ElMessage.warning('人工放行必须填写原因');return}await ElMessageBox.confirm(`确认人工放行 ${record.value.plateNumber}？`,'人工放行确认',{type:'warning'});exiting.value=true;try{await exitVehicle({parkingRecordId:record.value.id,action:'MANUAL_RELEASE',releaseReason:manual.reason});ElMessage.success('人工放行完成，车位已释放');manual.visible=false;record.value=undefined}finally{exiting.value=false}}
</script>
<template><div><h1 class="page-title">车辆出场</h1><p class="page-subtitle">查询场内记录和实时费用状态，再执行正常出场或人工放行。</p><section class="panel search"><el-form ref="formRef" :model="query" :rules="rules" inline @submit.prevent="search"><el-form-item prop="plateNumber"><el-input v-model="query.plateNumber" placeholder="输入车牌号码" clearable @keyup.enter="search"/></el-form-item><el-form-item><el-button type="primary" :loading="searching" @click="search">查询场内记录</el-button></el-form-item></el-form></section><section v-if="record" class="panel record"><div class="record-head"><div><h2>{{ record.plateNumber }}</h2><span>{{ record.recordNo }}</span></div><StatusTag :label="RECORD_STATUS[record.recordStatus]" :status="record.recordStatus"/></div><el-descriptions :column="2" border><el-descriptions-item label="停车场">{{ record.parkingLotName }}</el-descriptions-item><el-descriptions-item label="车位">{{ record.spaceCode }}</el-descriptions-item><el-descriptions-item label="入场时间">{{ formatDateTime(record.entryTime) }}</el-descriptions-item><el-descriptions-item label="停车时长">{{ record.parkingMinutes }} 分钟</el-descriptions-item><el-descriptions-item label="应付金额"><b class="money">{{ formatMoney(record.payableAmount) }}</b></el-descriptions-item><el-descriptions-item label="支付状态">{{ PAYMENT_STATUS[record.paymentStatus] }}</el-descriptions-item><el-descriptions-item label="月租车辆">{{ record.monthlyVehicle?'是（无需支付）':'否' }}</el-descriptions-item></el-descriptions><el-alert v-if="!record.monthlyVehicle&&record.paymentStatus!==1" title="临时车辆尚未支付，不能正常出场；可由车主完成模拟支付，特殊情况可人工放行。" type="warning" :closable="false" class="alert"/><div class="actions"><ConfirmButton text="正常出场" confirm-text="确认车辆已满足出场条件并释放车位？" type="success" :disabled="exiting||(!record.monthlyVehicle&&record.paymentStatus!==1)" @confirm="normalExit"/><el-button type="danger" :disabled="exiting" @click="manual.visible=true">人工放行</el-button></div></section><el-empty v-else description="输入车牌查询当前场内记录"/><el-dialog v-model="manual.visible" title="人工放行" width="min(500px,92vw)"><el-alert title="人工放行将跳过正常支付校验，原因会直接写入停车记录。" type="warning" :closable="false"/><el-input v-model="manual.reason" type="textarea" :rows="4" maxlength="200" show-word-limit placeholder="请填写特殊情况与放行原因" class="reason"/><template #footer><el-button @click="manual.visible=false">取消</el-button><el-button type="danger" :loading="exiting" @click="manualRelease">确认人工放行</el-button></template></el-dialog></div></template>
<style scoped>.search{margin-bottom:18px}.search .el-form-item{margin-bottom:0}.record{max-width:850px}.record-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:20px}.record-head h2{margin:0}.record-head span{color:var(--muted);font-size:13px}.alert{margin-top:18px}.actions{display:flex;gap:12px;justify-content:flex-end;margin-top:20px}.reason{margin-top:18px}</style>
